[tox]
min_version = 4.0
env_list =
    py{311,312,313}
    build_docs

[testenv]
description = run the test suite with {base_python}
extras =
    test
pass_env =
    CI
    CC
    LC_ALL
    LOCALE_ARCHIVE
set_env =
    MPLBACKEND = agg
change_dir = {toxworkdir}/{env_name}
commands =
    pytest --pyargs sora --cov=sora --cov-report=xml:coverage.xml --cov-report=term-missing {posargs}

[testenv:build_docs]
description = build the Sphinx documentation
change_dir = docs
extras =
    docs
commands =
    sphinx-build -j auto --color --keep-going -b html -d _build/.doctrees . _build/html {posargs}
