blank_issues_enabled: false

contact_links:
  - name: Questions and discussions
    url: https://sora.readthedocs.io/latest/team.html#contact-us
    about: Ask questions or discuss ideas that are not yet ready to become an issue.